### ISSUE TITLE
Richmond VA goes to Richmond CA instead

### ISSUE THREAD

**Issue by nvkelso** [mapzen/ui#30]
The lat/lng needs to be updated

**Comment by nvkelso** [comment]
Hat tip to @IndyHurt for finding this as part of Targeted Editing blog series.

**Comment by louh** [comment]
We'd been blocked on deploying this because the location of mapzen-ui.js was changed and there were some CORS settings that needed to be set, which have been addressed in https://github.com/mapzen/operations-engineering/issues/21.

This change is now deployed, but pages that use mapzen-ui.js should update their script sources to `https://mapzen.com/common/ui/mapzen-ui.min.js` to get the new stuff.
